export const ERROR = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  FATAL_ERROR: 'FATAL_ERROR',
  ENTRY_EXISTS: 'ENTRY_EXISTS',
  ENTRY_DELETED: 'ENTRY_DELETED',
  ENTRY_NOT_FOUND: 'ENTRY_NOT_FOUND',
  AUTHORISATION_ERROR: 'AUTHORISATION_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  PERMISSION_ERROR: 'PERMISSION_ERROR',
  TOKEN_INVALID: 'TOKEN_INVALID',
};

export const ROOM_STATUS = ['AVAILABLE', 'RESERVED', 'PENDING_APPROVAL'];
